[package]
name = "monitoring-backend"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
diesel = { version = "1.4.6", features = ["postgres"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
default-features = false
features = ["diesel_postgres_pool"]
