name: Deploy to server

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./charts-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "charts-frontend/public/"
          REMOTE_HOST: "plants.business"
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
